---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: ../modified_svm-latex-cv.tex
mainfont: Times New Roman
geometry: margin=1in

title: "CV"
author: Yinbo Wu

# jobtitle: "Chief Brewer, Arthur Guinness & Son"
# address: "Guinness Brewery · Park Royal · London NW10 7RR, UK"
fontawesome: no
email: yinbo.wu@huskers.unl.edu
# github: svmiller
# twitter: stevenvmiller
#osf: "Enter 5 digit osf string here"
# phone: "+353 1 408 4800"
# web: guinness.com
updated: no

keywords: R Markdown, academic CV, template

# fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: black
urlcolor: black
---


## **Academic Positions**
* 2021  Postdoctoral fellow, Department of Special Education & Communication Disorders, University of Nebraska-Lincoln
  * Project: “Neural predictors of speech perception in adults with Cochlear Implants”

## **Education**
* 2020 Ph.D., Developmental Psychology, University of Nebraska-Lincoln, USA
  * Dissertation: “The association between parenting, attention and working memory in early childhood”
* 2018 M.A., Developmental Psychology, University of Nebraska-Lincoln, USA
  * Thesis: “The developmental trajectory of unfocused play and its relationship with maternal sensitivity”
* 2014 M.EDU., Applied Psychology, Soochow University, China  
  * Thesis: “Family structures and marital relations in different demographic groups”
* 2011  B.S., Applied Psychology, Soochow University, China

## **Fellowships and Awards**
2019  Buffett Institute Graduate Fellowship, The Buffett Early Childhood Institute  
2019  Warden Research Fellowship, University of Nebraska-Lincoln  
2019, 2017  RAC/Warden Travel Award, University of Nebraska-Lincoln  
2014, 2011  Outstanding Graduate Award, Soochow University

## **Publications**

1. Schutte, A. R., **Wu, Y**., & Jacoby, M. (2022). Individual differences in executive attention and inhibitory control are related to spatial memory biases in adults. *Quarterly Journal of Experimental Psychology*.
1. **Wu, Y**., & Schutte, A. R. (2021). Attentional shifting mediates the relationship between parenting and working memory. *Journal of Cognition and Development*, *22*(5), 667-677. doi: 10.1080/15248372.2021.1976781
1. **Wu, Y**., & Schutte, A. R. (2020). Test of a relationship between spatial working memory and perception of symmetry axes in 3- to 6-year olds. *Spatial Cognition and Computation*, *20*(2), 104-133. doi: 10.1080/13875868.2020.1731515
1. **Wu, Y**., & Schutte, A. R. (under review). Parenting and attention are related to spatial memory in early childhood.
1. Schutte, A. R. & **Wu, Y**. (under revision). Head injury is associated with subtle spatial memory impairment in adults. 

## **Conference Presentations**

1. Jacoby, M. N., **Wu, Y**., & Schutte, A. R. (2021, May). *Cognitive control is related to spatial memory biases in adults*. Poster presented at the Visual Sciences Society Conference, St. Pete Beach, FL
1. **Wu, Y**. & Schutte, A. R. (2021, April). *Attentional shifting mediates the relationship between parenting and working memory*. Paper presented at the Society for Research in Child Development Virtual Biennial Meeting.
1. **Wu, Y**. & Schutte, A. R. (2021, April). *Parenting, attention and verbal and spatial working memory in early childhood*. Poster presented at the Society for Research in Child Development Virtual Biennial Meeting.
1.**Wu, Y**. & Schutte, A. R. (2021, June). *Parenting, attention and working memory in early childhood*. Paper presented at the 50th Virtual Annual Meeting of The Jean Piaget Society. 
1. **Wu, Y**. & Schutte, A. R. (2019, October). *Age of traumatic brain injury (TBI) is associated with spatial memory impairments*. Poster presented at the Cognitive Development Society Conference, Louisville, KY.
1. **Wu, Y**. & Schutte, A. R. (2018, October). *Developmental changes in unfocused play and the relationship with maternal sensitivity in early childhood*. Paper presented at the SRCD Conference on the Use of Secondary and Open Source Data, Phoenix, AZ.
1. **Wu, Y**. & Schutte, A. R. (2017, April). *A relationship between spatial memory biases and perception of symmetry axes in early childhood*. Poster presented at the Society for Research in Child Development Biennial Meeting, Austin, TX.

## **Teaching Experiences**
### *Instructor*
1. 2020 PSYC 289: Developmental Psychology, University of Nebraska-Lincoln
1. 2018, 2017 PSY 350: Research Methods and Analysis, University of Nebraska-Lincoln  
  
### *Teaching Assistant*
1. 2019 PSYC 273: Brain and Behavior, University of Nebraska-Lincoln
1. 2018 PSY 948: Structural Equation Modeling in the Behavior Sciences, University of Nebraska-Lincoln
1. 2018 PSYC 330: Psychology of Diversity, University of Nebraska-Lincoln
1. 2016 PSYC 489: Child Behavior and Development, University of Nebraska-Lincoln  

## **Statistical Training Workshops**

Data Visualization   
Latent Growth Curve Modeling    
Multilevel Modeling: A Second Course  
Multilevel and Mixed Models Using R  
Power Analysis  
Structural Equation Modeling 


## **Service Activities**

2018-2020 Treasurer, Graduate Association Assembly, University of Nebraska-Lincoln  
2019           Evaluator, Undergraduate Creative and Research Experience, University of Nebraska-Lincoln   
2019           Judge, Undergraduate Student Research Poster session, University of Nebraska-Lincoln     
2016           Exhibitor, Sunday with a scientist, Nebraska State Museum


## **Professional Societies**
American Psychological Association  
Cognitive Development Society  
Jean Piaget Society  
Society for Research in Child Development
